[package]
name = "quantsupport-xll"
version.workspace = true
edition = "2021"
description = "Excel XLL bindings for QuantSupport"
license = "MIT"
repository = "https://github.com/jmelo11/quantsupport"
publish = false

[lib]
name = "quantsupport_xll"
crate-type = ["cdylib"]

[dependencies]
quantsupport = { path = "../.." }

[target.'cfg(all(windows, target_arch = "x86_64"))'.dependencies]
xll-rs = "0.1.1"

[target.'cfg(all(windows, target_arch = "x86_64"))'.build-dependencies]
xll-rs = "0.1.1"